In [91]:
import numpy as np

In [92]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10] , [11, 12, 13, 14, 15]])

In [93]:
dimensions = arr.shape

In [94]:
r , c = dimensions

In [95]:
print("Rows    : ", r)
print("Columns : " , c)

Rows    :  3
Columns :  5


In [87]:
print("Array with ", r , " Rows and ",  c , " Columns \n\n" , arr)

Array with  3  Rows and  5  Columns 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [96]:
sum = 0 
for i in range(0, r):
    for j in range(0 , c):
        sum = sum + arr[i][j]

In [97]:
print("Sum of Array is : " , sum)

Sum of Array is :  120
